name: Build → Push Image → GitOps Update

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      branch:
        required: true
        type: string
      environment:
        type: string
        default: "dev"
      gitops_repo:
        required: true
        type: string

    secrets:
      GHCR_TOKEN:
        required: true
      GITOPS_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout service repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OWNER }}/${{ inputs.app_name }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Capture service commit SHA
        id: meta
        run: |
          SHA=$(git rev-parse --short=7 HEAD)
          TAG="${{ inputs.branch }}-${SHA}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using image tag: $TAG"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Multi-Arch Image
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ inputs.app_name }}:${{ inputs.branch }}
            ghcr.io/${{ env.OWNER }}/${{ inputs.app_name }}:${{ steps.meta.outputs.tag }}

    outputs:
      tag: ${{ steps.meta.outputs.tag }}

  update_gitops:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.gitops_repo }}
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update image tag in GitOps
        run: |
          FILE="apps/${{ inputs.app_name }}/overlays/${{ inputs.environment }}/patch-image.yaml"
          
          yq eval "
            .spec.template.spec.containers[0].image =
            \"ghcr.io/${{ env.OWNER }}/${{ inputs.app_name }}:${{ needs.docker.outputs.tag }}\"
          " -i "$FILE"

      - name: Commit & Push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          
          # Prevent failure when no changes exist
          if git diff --cached --quiet; then
            echo "No GitOps changes detected — skipping commit."
            exit 0
          fi
          git commit -m "Update image tag → ${{ inputs.app_name }}:${{ needs.docker.outputs.tag }}"
          git push
